### ISSUE TITLE
Code into Arduino UNO?

### ISSUE THREAD

**Issue by sudoMakeThisSecure** [AlbertGBarber/Infinity-Dodecahedron#1]
Hay mate. Don't use Git much, and couldn't find contact details, so posting here sorry.
I am making an infinity dodecahedron, like yours, just bigger, with 150mm edges and 330 ws2815 LEDs (144/M strip still).
I don't really want to make the PCB for the controller, due to the cost and my poor soldering skill haha, so was wondering if i could slap your code into an Arduino UNO?

**Comment by AlbertGBarber** [comment]
While the Uno is capable of controlling the Leds, it will probably not have enough memory to compile/run the code. You can solve this by removing some of the effects. 

You'll have to modify the code quite a bit anyway to remove the ESP parts (mostly the button handling and eeprom stuff, which is not needed), but also update the segment layouts for your strips.

It will be much easier to just use my controller pcb. You can buy custom pcb's for $5 or less at many Chinese board houses (JLCPCB, Allpcb, etc), with most offering fairly cheap shipping. The cost should be small compared with the rest of the project materials.

Likewise, soldering the pcb is easy compared to soldering the strips. Building a dodecahedron is **not** for novice solderers due to the finickyness of the strip pads and the risk of heat damage to the leds. I had to replace a number of strip sections when building my dodecahedron.

**Comment by sudoMakeThisSecure** [comment]
Sounds good. I will go with your PCB then. Cheers mate
